//create
localStorage.setItem("key","value");
localStorage.setItem("sum",10);
let p = {
    name: 'sujal',
    age: 21
}
localStorage.setItem("Person",JSON.stringify(p));

//read
//localStorage.getItem('key');  
let val = localStorage.getItem("key");
console.log(val);

//delete
//localStorage.removeItem("key");

//clear
//localStorage.clear();

//session strg
//similar to local storage but last only inti the browser tab close
// also store in key value pairs
//max siz 5mb
//data is not stored permently

//benifits:
//tempory data
// Save data
sessionStorage.setItem("theme", "dark");

// Get data
console.log(sessionStorage.getItem("theme")); // "dark"

// Clear session storage
//sessionStorage.clear();

//remove item
//sessionStorage.removeItem("theme");

//check if item exists
if (sessionStorage.getItem("theme")) {
    console.log("Theme is dark");
} else {
    console.log("Theme is light");
}

//get all keys
for(let i=0;i<sessionStorage.length;i++){
    console.log(sessionStorage.key(i));
}


//cookies
//small text file that stores info about user activity on a website
//stored in key value pair
//max size of cookie is 4kb
//can be accessed by server and client side js
//secure, httpOnly, expires, domain,path,sameSite
//cookie-parser middleware is used to parse cookies
//express-session middleware is used to create session
//session id is stored in cookie
//eg:

// Set a cookie
document.cookie = "username=Sujal; expires=Fri, 31 Dec 2025 12:00:00 UTC; path=/";
// username: Key
// Sujal: Value
// expires: Expiration date
// path: Where this cookie is accessible (/ means entire site)

// Read cookies
console.log(document.cookie);

//update
document.cookie = "username=Raj; expires=Fri, 31 Dec 2025 23:59:59 GMT; path=/";

//delete
//document.cookie = "username=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/";

//

// 4. IndexedDB
// A NoSQL database inside the browser
// Stores large amounts of structured data
// Asynchronous & supports indexes.
// Used for offline apps, storing files, caching data.
// Can have multiple databases.
// Data can be queried using SQL-like syntax.
// Supports transactions.
// Uses object stores to organize data.
// Can use cursors to iterate over data.
// Can use events to listen for changes.
// Can use indexedDB.open() to open a connection to a database.
// Can use indexedDB.close() to close a connection to a database.
// Can use indexedDB.deleteDatabase() to delete a database.
// Can use indexedDB.transaction() to start a transaction.

let request = indexedDB.open("MyDatabase", 1);

request.onupgradeneeded = function(event) {
  let db = event.target.result;
  db.createObjectStore("users", { keyPath: "id" });
};

request.onsuccess = function(event) {
  console.log("Database opened successfully!");
};


// 5. Cache API (Service Workers)
// Stores HTTP responses for offline-first PWAs.
// Typically used with service workers.
// Allows you to cache static assets like images, stylesheets, scripts, etc.
// Also allows you to cache dynamic content generated by your app.
// Can be used to implement offline-first strategies./
// Can be used to implement push notifications.

// Create a new cache
// Open or create a cache
caches.open('my-cache-v1').then(cache => {
  // Add a resource to cache
  cache.add('/index.html');

  // Add multiple resources
  cache.addAll([
    '/styles.css',
    '/script.js',
    '/logo.png'
  ]);
});


// Check if an asset is cached
caches.match("/v1.js").then(function(response) {
  if (response) {
    console.log("Asset found in cache!");
  } else {
    console.log("Asset not found in cache.");
  }
})